import React from "react";
import {
  ArrowDownLeft,
  ArrowUpRight,
  Bell,
  Camera,
  Check,
  ChevronRight,
  CircleCheck,
  Clock,
  Cloud,
  Copy,
  Cpu,
  CreditCard,
  Download,
  Eye,
  FileText,
  Fingerprint,
  Flag,
  Image as ImageIcon,
  Info,
  Landmark,
  LayoutGrid,
  Lock,
  LogOut,
  Mic,
  Pause,
  Plus,
  Radar,
  ReceiptText,
  RotateCw,
  Search,
  SendHorizontal,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  TrendingUp,
  TriangleAlert,
  User,
  Users,
  Wifi,
  X,
  House,
  type LucideIcon,
} from "lucide-react";

/* Professional icon set (Lucide) behind the app's existing Icon API,
   so every screen picks the new glyphs up without changes. */
const ICONS: Record<string, LucideIcon> = {
  home: House,
  send: SendHorizontal,
  shield: Shield,
  "shield-check": ShieldCheck,
  lock: Lock,
  fingerprint: Fingerprint,
  camera: Camera,
  image: ImageIcon,
  check: Check,
  "check-circle": CircleCheck,
  x: X,
  alert: TriangleAlert,
  info: Info,
  users: Users,
  chevron: ChevronRight,
  eye: Eye,
  out: ArrowUpRight,
  in: ArrowDownLeft,
  sparkles: Sparkles,
  radar: Radar,
  bank: Landmark,
  refresh: RotateCw,
  clock: Clock,
  pause: Pause,
  doc: FileText,
  bell: Bell,
  phone: Smartphone,
  wifi: Wifi,
  receipt: ReceiptText,
  card: CreditCard,
  plus: Plus,
  copy: Copy,
  logout: LogOut,
  flag: Flag,
  grid: LayoutGrid,
  user: User,
  search: Search,
  download: Download,
  cpu: Cpu,
  cloud: Cloud,
  mic: Mic,
  trend: TrendingUp,
};

export function Icon({
  name,
  size = 22,
  className,
  strokeWidth = 2,
  style,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
  style?: React.CSSProperties;
}) {
  const C = ICONS[name];
  if (!C) return null;
  return <C size={size} strokeWidth={strokeWidth} className={className} style={style} aria-hidden absoluteStrokeWidth={false} />;
}
